# forums
forum_latest_topics:
  url:  /forums/latest-topics
  param: { module: sfSimpleForum, action: latestTopics }

forum_latest_topics_feed:
  url:  /forums/latest-topics-feed
  param: { module: sfSimpleForum, action: latestTopicsFeed }

forum_latest_posts:
  url:  /forums/latest-posts
  param: { module: sfSimpleForum, action: latestPosts }

forum_latest_posts_feed:
  url:  /forums/latest-posts-feed
  param: { module: sfSimpleForum, action: latestPostsFeed }

forum_home:
  url:  /forums
  param: { module: sfSimpleForum, action: index }

forum_home_list:
  url:  /forums
  param: { module: sfSimpleForum, action: forumList }

forum_name:
  url:  /forums/:forum_name
  param: { module: sfSimpleForum, action: forum }

forum_name_last:
  url:  /forums/:forum_name/lastest-posts
  param: { module: sfSimpleForum, action: forumLatestPosts }

forum_name_last_feed:
  url:  /forums/:forum_name/lastest-posts-feed
  param: { module: sfSimpleForum, action: forumLatestPostsFeed }

forum_topic:
  url:  /forums/topic/:id/:stripped_title
  param: { module: sfSimpleForum, action: topic }

forum_topic_feed:
  url:  /forums/topic-feed/:id/:stripped_title
  param: { module: sfSimpleForum, action: topicFeed }

forum_message:
  url:  /forums/view-post/:id
  param: { module: sfSimpleForum, action: post }

forum_new_topic:
  url:  /forums/new-topic/:forum_name
  param: { module: sfSimpleForum, action: createTopic }

forum_user:
  url:  /user/:username/posts
  param: { module: sfSimpleForum, action: userLatestPosts }

forum_user_feed:
  url:  /user/:username/posts-feed
  param: { module: sfSimpleForum, action: userLatestPostsFeed }

forum_user_topics:
  url:  /user/:username/topics
  param: { module: sfSimpleForum, action: userLatestTopics }

forum_user_topics_feed:
  url:  /user/:username/topics-feed
  param: { module: sfSimpleForum, action: userLatestTopicsFeed }

forum_delete_post:
  url: /forums/delete-post/:id
  param: { module: sfSimpleForum, action: deletePost }

forum_create_topic:
  url: /forums/create-topic
  param: { module: sfSimpleForum, action: createTopic }

forum_delete_topic:
  url: /forums/delete-topic/:id
  param: { module: sfSimpleForum, action: deleteTopic }

forum_report_abuse:
  url: /forums/report-topic/:id
  param: { module: sfSimpleForum, action: reportAbuse }

forum_recommand:
  url: /forums/recommand-topic/:id
  param: { module: sfSimpleForum, action: recommand }

forum_unrecommand:
  url: /forums/unrecommand-topic/:id
  param: { module: sfSimpleForum, action: unrecommand }

forum_toggle_lock:
  url: /forums/toggle-lock/:id
  param: { module: sfSimpleForum, action: toggleLock }

forum_toggle_stick:
  url: /forums/toggle-stick/:id
  param: { module: sfSimpleForum, action: toggleStick }
